### ISSUE TITLE
"There was an error sending the test notification. Please check your notification settings and try again"

### ISSUE THREAD

**Issue by matda59** [jellyfin/jellyfin-plugin-pushbullet#10] opened 2020-04-21 11:48 UTC
Version: 10.5.0
Operating System: Windows
Architecture: X64

installed Pushbullet 3.0,0,0 

put in the Pushbullet channel and auth token - get the error:

"There was an error sending the test notification. Please check your notification settings and try again"
console log:
[21:39:28] [ERR] [27] Emby.Server.Implementations.HttpServer.HttpListenerHost: Could not find handler for /Notification/Pushbullet/Test/fd05c8150bce4652800e81887f42d32f
[21:39:28] [ERR] [27] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: Unable to find the specified file.

**Comment by JustAMan** [comment] 2020-04-29 15:49
Most likely a duplicate of https://github.com/jellyfin/jellyfin-plugin-pushbullet/issues/5, should be fixed in next release. Feel free to re-open if it isn't fixed.

**Closed as completed by JustAMan** 2020-04-29 15:49 UTC
Labels: duplicate
